language: node_js

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

sudo: false

notifications:
  email:
    recipients:
      - charlesg@convertigo.com
    on_success: change # default: change
    on_failure: change # default: always

node_js:
  - '10'

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_install:
  - export CHROME_BIN=chromium-browser

before_script:
  - npm prune

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -s -c /tmp/cookies "https://ci-develop.convertigo.net/convertigo/admin/services/engine.CheckAuthentication"
  - curl -b /tmp/cookies -s "https://ci-develop.convertigo.net/convertigo/admin/services/engine.GetStatus"
  - export BUILD_VERSION=$(curl -b /tmp/cookies -s "https://ci-develop.convertigo.net/convertigo/admin/services/engine.GetStatus" | sed -n -e "s,.*build.*version=\"\(.*\)\".*,\\1,p")

addons:
  artifacts:
    target_paths: convertigo-$BUILD_VERSION/qualif/c8osdk-js